# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simhyd_sim <- function(P, E, INSC, COEFF, SQ, SMSC, SUB, CRAK, K, GWt0, SMSt0) {
    .Call('_hydromad_simhyd_sim', PACKAGE = 'hydromad', P, E, INSC, COEFF, SQ, SMSC, SUB, CRAK, K, GWt0, SMSt0)
}

