# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simhyd_sim <- function(P, E, INSC, COEFF, SQ, SMSC, SUB, CRAK, K) {
    .Call('hydromad_simhyd_sim', PACKAGE = 'hydromad', P, E, INSC, COEFF, SQ, SMSC, SUB, CRAK, K)
}

